// <auto-generated />
namespace ForumGenerator_Version2_Server.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changeAdminCreation4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeAdminCreation4));
        
        string IMigrationMetadata.Id
        {
            get { return "201305312154550_changeAdminCreation4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
