// <auto-generated />
namespace ForumGenerator_Version2_Server.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class RegPolicy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegPolicy));
        
        string IMigrationMetadata.Id
        {
            get { return "201307312251024_RegPolicy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
